### ISSUE TITLE
[TA Code Review] for MAN JUNCHENG

### ISSUE THREAD

**Issue by kohnh** [AY2324S1-CS2113-W12-1/tp#105]
@spinoandraptos
Good job adding JavaDocs for the majority of the functions.
- [x] Try to abstract your code and not have too deep nesting
- [x] Try to shorten your methods like `parseStartCommand`
- [x] Try not to repeat yourself by abstracting parts of your code especially the string literals
- [x] Try to give more meaningful JavaDocs

**Comment by spinoandraptos** [comment]
Deep nesting: categorise by module,
Shorter: StartCommand and EditCommand

**Comment by spinoandraptos** [comment]
@kohnh may I know what you are referring to for "Try not to repeat yourself by abstracting parts of your code especially the string literals"?

**Comment by lisizhuang-0121** [comment]
@spinoandraptos I guess we could use functions to display a standard set of Strings instead of having repeated println statements of the same string

**Comment by kohnh** [comment]
@lisizhuang-0121 that is an excellent suggestion. The string literals that I am referring to for example are either declared strings like `String s ="hello"` or when you `println`. If you find that you are repeatedly copy pasting lines of code, it is good practice to see if you can abstract something common to make it easier both for you and anyone who is trying to understand your code
