### ISSUE TITLE
[PE-D][Tester E] Conflicting information about whether finding by module is a feature or not

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-W12-1/tp#152]
In the UG, the "Command Summary" paragraph lists finding by module as a feature (using the "find /[module]" command format). But in the "Find question/answer `find`" paragraph, finding by module is not listed as a feature. 

![image.png](https://raw.githubusercontent.com/wendelinwemhoener/ped/main/files/2c40693c-8964-4d05-b5bb-3bbe700461d1.png)

![image.png](https://raw.githubusercontent.com/wendelinwemhoener/ped/main/files/bbcca7b2-5eb6-411f-b28f-3bbd2871d4f1.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: wendelinwemhoener/ped#4

**Comment by lisizhuang-0121** [comment]
Finding by module is a feature, the description for find command in the UG will be updated.
