### ISSUE TITLE
[PE-D][Tester A] Find command does not have `/answer` tag

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-W12-1/tp#170]
Cannot find based on answer according to the user guide

![image.png](https://raw.githubusercontent.com/TongZhengHong/ped/main/files/eaec4aa4-bc2f-4865-a2fc-7b54fbf4e24a.png)

![image.png](https://raw.githubusercontent.com/TongZhengHong/ped/main/files/361c8a43-33e2-4d1d-ad94-63bc0333bff6.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: TongZhengHong/ped#3

**Comment by lisizhuang-0121** [comment]
This is a duplicate command as #151 as we have generalized searching of questions or answers to /description
We would work on issue 151 instead.
