### ISSUE TITLE
[PE-D][Tester E] "Short" command doesn't allow using slashes in the question description or answer

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-W12-1/tp#172]
When using the "short" command to add a new question: When using a slash (or multiple slashes) in the question description, the new question isn't added to the collection and instead, an error message is shown.

See screenshot: 
![image.png](https://raw.githubusercontent.com/wendelinwemhoener/ped/main/files/c303ec45-d8ab-461b-82a6-4b1467c5a13f.png)

Nothing in the UG indicates that slashes aren't allowed to be used in the question description or answer of the "short" command.

The same problem applies to the answer part, see screenshot:

![image.png](https://raw.githubusercontent.com/wendelinwemhoener/ped/main/files/61451fd4-0638-4ec4-8dbe-f9e2333311d5.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: wendelinwemhoener/ped#14

**Comment by lisizhuang-0121** [comment]
This is a duplicate issue as #153 
We will focus on issue 153 instead.
