### ISSUE TITLE
[PE-D][Tester B] shuffle command has no output when questions are successfully shuffled

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-W12-1/tp#176]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
**Description**

`shuffle` command has no output when questions are successfully shuffled

**Steps to Reproduce**
1. Run the app
2. Add at least 2 questions
3. Run the `shuffle` command

**Expected Output**

`shuffle` command should inform the user if the questions were successfully shuffled.

**Actual Output**
```
shuffle
    ____________________________________________________________

    ____________________________________________________________
```
**Screenshot**
You can see in the image below that the questions have been successfully shuffled, but the `shuffle` command gives no indication of that.

![image.png](https://raw.githubusercontent.com/imaginarys96/ped/main/files/0cbe02ab-3f1a-4df2-abb7-8d5cfe5feb72.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: imaginarys96/ped#6

**Comment by lisizhuang-0121** [comment]
This is a duplicate issue as #168 .
We will focus on issue 168 instead.
